name: primitive-ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  APP_DIR: ai-image-captioner 

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable npm cache (client)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ env.APP_DIR }}/client/package-lock.json

      - name: Install (client)
        working-directory: ${{ env.APP_DIR }}/client
        run: npm ci || npm install

      - name: Lint (client)
        working-directory: ${{ env.APP_DIR }}/client
        run: npm run lint --if-present

      - name: Test (client) with coverage (if present)
        working-directory: ${{ env.APP_DIR }}/client
        run: npm test -- --coverage --run --watch=false || echo "no client tests"

      - name: Build (client)
        working-directory: ${{ env.APP_DIR }}/client
        run: npm run build --if-present

      - name: Enable npm cache (server)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ env.APP_DIR }}/server/package-lock.json

      - name: Install (server)
        working-directory: ${{ env.APP_DIR }}/server
        run: npm ci || npm install

      - name: Lint (server)
        working-directory: ${{ env.APP_DIR }}/server
        run: npm run lint --if-present

      - name: Test (server) with coverage (if present)
        working-directory: ${{ env.APP_DIR }}/server
        run: npm test -- --coverage --ci || echo "no server tests"

      - name: Build (server)
        working-directory: ${{ env.APP_DIR }}/server
        run: npm run build --if-present

      - name: Upload client dist
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: client-dist
          path: ${{ env.APP_DIR }}/client/dist

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            ${{ env.APP_DIR }}/client/coverage
            ${{ env.APP_DIR }}/server/coverage
