name: CI/CD-Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20 (cache both apps)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            client/package-lock.json
            server/package-lock.json

      - name: Install (client)
        working-directory: client
        run: npm ci

      - name: Lint (client)
        working-directory: client
        run: npm run lint --if-present

      - name: Test (client) with coverage (if present)
        working-directory: client
        run: npm test -- --coverage --run --watch=false || echo "no client tests"

      - name: Build (client)
        working-directory: client
        run: npm run build --if-present

      - name: Install (server)
        working-directory: server
        run: npm ci

      - name: Lint (server)
        working-directory: server
        run: npm run lint --if-present

      - name: Test (server) with coverage (if present)
        working-directory: server
        run: npm test -- --coverage --ci || echo "no server tests"

      - name: Build (server)
        working-directory: server
        run: npm run build --if-present

      # ----- Artifacts (optional but handy for debugging) -----
      - name: Upload client dist
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: client-dist
          path: client/dist

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            client/coverage
            server/coverage

      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} 
          files: |
            client/coverage/lcov.info
            server/coverage/lcov.info
          flags: client,server
          fail_ci_if_error: false
